// Top-level build file where you can add configuration options common to all sub-projects/modules.

plugins {
    id 'com.android.application' apply false
    id 'com.android.library' apply false
}

allprojects {
    layout.buildDirectory = file('../../../build_android')
}

task clean(type: Delete) {
    delete rootProject.layout.buildDirectory
}
