pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    plugins {
        id 'com.android.application' version '8.9.1'
        id 'com.android.library' version '8.9.1'
    }
}
System.setProperty("AX_ROOT", new File(settingsDir, "../../thirdparty/port/axmol").canonicalPath)
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

include ':libaxmol'
project(':libaxmol').projectDir = new File(settingsDir, '../../thirdparty/port/axmol/core/platform/android/libaxmol')
include ':krkr2yuri'
project(':krkr2yuri').projectDir = new File(settingsDir, 'app')
